# Helper Script: Prepare Terraform Variables
# This script helps you generate the required values for terraform.tfvars

Write-Host "=== Azure Application Gateway Lab - Setup Helper ===" -ForegroundColor Cyan
Write-Host ""

# 0. Azure Authentication
Write-Host "0. Azure Authentication (Service Principal)" -ForegroundColor Yellow
Write-Host "   Enter your Azure Subscription ID:" -ForegroundColor Gray
$subscriptionId = Read-Host
Write-Host "   Enter your Azure Tenant ID:" -ForegroundColor Gray
$tenantId = Read-Host
Write-Host "   Enter your Azure Client ID (Service Principal):" -ForegroundColor Gray
$clientId = Read-Host
Write-Host "   Enter your Azure Client Secret:" -ForegroundColor Gray
$clientSecretInput = Read-Host -AsSecureString
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($clientSecretInput)
$clientSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

Write-Host ""
Write-Host "   Azure credentials captured" -ForegroundColor Green
Write-Host ""

# 1. Generate SSH Key
Write-Host "1. SSH Key Generation" -ForegroundColor Yellow
Write-Host "   Do you need to generate an SSH key? (Y/N)" -ForegroundColor Gray
$generateSsh = Read-Host
if ($generateSsh -eq "Y" -or $generateSsh -eq "y") {
    $sshKeyPath = "$HOME\.ssh\appgw_lab_rsa"
    Write-Host "   Generating SSH key at: $sshKeyPath" -ForegroundColor Green
    ssh-keygen -t rsa -b 4096 -f $sshKeyPath -N '""'
    Write-Host "   SSH key generated" -ForegroundColor Green
    $sshPublicKey = Get-Content "$sshKeyPath.pub" -Raw
} else {
    Write-Host "   Enter the path to your SSH public key:" -ForegroundColor Gray
    $sshKeyPath = Read-Host
    $sshPublicKey = Get-Content $sshKeyPath -Raw
}

Write-Host ""
Write-Host "   Your SSH Public Key:" -ForegroundColor Green
Write-Host "   $sshPublicKey" -ForegroundColor White
Write-Host ""

# 2. Convert SSL Certificate to Base64
Write-Host "2. SSL Certificate Conversion" -ForegroundColor Yellow
Write-Host "   Enter the path to your PFX certificate file:" -ForegroundColor Gray
Write-Host "   (Default: c:\TFE\AppGateway\appgw-cert.pfx)" -ForegroundColor Gray
$certPath = Read-Host
if ([string]::IsNullOrWhiteSpace($certPath)) {
    $certPath = "c:\TFE\AppGateway\appgw-cert.pfx"
}

if (Test-Path $certPath) {
    $certBytes = [IO.File]::ReadAllBytes($certPath)
    $certBase64 = [Convert]::ToBase64String($certBytes)
    
    # Save to file
    $certBase64 | Out-File "cert_base64.txt" -Encoding ASCII
    
    Write-Host "   Certificate converted to base64" -ForegroundColor Green
    Write-Host "   Saved to: cert_base64.txt" -ForegroundColor Green
    Write-Host ""
    Write-Host "   First 100 characters of base64 certificate:" -ForegroundColor Green
    Write-Host "   $($certBase64.Substring(0, [Math]::Min(100, $certBase64.Length)))..." -ForegroundColor White
} else {
    Write-Host "   Certificate file not found: $certPath" -ForegroundColor Red
    $certBase64 = ""
}

Write-Host ""

# 3. Certificate Password
Write-Host "3. Certificate Password" -ForegroundColor Yellow
Write-Host "   Does your PFX certificate have a password? (Y/N)" -ForegroundColor Gray
$hasPassword = Read-Host
$certPassword = ""
if ($hasPassword -eq "Y" -or $hasPassword -eq "y") {
    Write-Host "   Enter certificate password:" -ForegroundColor Gray
    $certPasswordSecure = Read-Host -AsSecureString
    $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($certPasswordSecure)
    $certPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
}

Write-Host ""

# 4. Generate terraform.tfvars
Write-Host "4. Generating terraform.tfvars" -ForegroundColor Yellow

$tfvarsContent = @"
# Azure Application Gateway Lab - Terraform Variables
# Auto-generated by setup-helper.ps1

# Azure Authentication
azure_subscription_id = "$subscriptionId"
azure_tenant_id       = "$tenantId"
azure_client_id       = "$clientId"
azure_client_secret   = "$clientSecret"

# Basic Configuration
resource_group_name = "rg-appgw-lab"
location            = "centralindia"

# Application Gateway Configuration
appgw_name     = "appgw-lab-basic"
appgw_sku_tier = "Standard_v2"
appgw_capacity = 1
waf_mode       = "Detection"

# VM Configuration
vm_size        = "Standard_B2s"
admin_username = "azureuser"

# SSH Public Key
ssh_public_key = "$($sshPublicKey.Trim() -replace '\\', '\\\\')"

# SSL Certificate (base64-encoded PFX)
ssl_certificate_data     = "$certBase64"
ssl_certificate_password = "$certPassword"

# Monitoring
enable_diagnostics           = true
log_analytics_workspace_name = "law-appgw-lab"
"@

$tfvarsContent | Out-File "terraform.tfvars" -Encoding UTF8

Write-Host "   terraform.tfvars created successfully!" -ForegroundColor Green
Write-Host ""

# 5. Summary
Write-Host "=== Setup Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Review terraform.tfvars and adjust settings if needed" -ForegroundColor White
Write-Host "2. Run: terraform init" -ForegroundColor White
Write-Host "3. Run: terraform plan" -ForegroundColor White
Write-Host "4. Run: terraform apply" -ForegroundColor White
Write-Host ""
Write-Host "Files created:" -ForegroundColor Yellow
Write-Host "  - terraform.tfvars (main configuration)" -ForegroundColor White
Write-Host "  - cert_base64.txt (certificate backup)" -ForegroundColor White
if ($generateSsh -eq "Y" -or $generateSsh -eq "y") {
    Write-Host "  - $sshKeyPath (private key)" -ForegroundColor White
    Write-Host "  - $sshKeyPath.pub (public key)" -ForegroundColor White
}
Write-Host ""
Write-Host "Important: Keep terraform.tfvars secure - it contains sensitive data!" -ForegroundColor Red
Write-Host ""
